### Get profile
GET http://localhost:3000/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjJlYzIwNC1iNTBiLTRmNDEtYjhhOC00OTliODU4YTM5MWUiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc3MTE1ODQ4LCJleHAiOjE3NzcxMTY3NDh9.18sF0iY-M1M-b84lT4X5Q4eO7l2bV6p6F6wB3W7C8R4

### Update profile
PATCH http://localhost:3000/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjJlYzIwNC1iNTBiLTRmNDEtYjhhOC00OTliODU4YTM5MWUiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc3MTE1ODQ4LCJleHAiOjE3NzcxMTY3NDh9.18sF0iY-M1M-b84lT4X5Q4eO7l2bV6p6F6wB3W7C8R4

{
    "name": "New Name",
    "department": "New Department",
    "companyName": "New Company Name"
}

### Change password
PATCH http://localhost:3000/users/profile/change-password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MjJlYzIwNC1iNTBiLTRmNDEtYjhhOC00OTliODU4YTM5MWUiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzc3MTE1ODQ4LCJleHAiOjE3NzcxMTY3NDh9.18sF0iY-M1M-b84lT4X5Q4eO7l2bV6p6F6wB3W7C8R4

{
    "oldPassword": "Admin123",
    "newPassword": "Admin124"
}
